server:
  port: 8080

spring:
  application:
    name: vtswebapiconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vsouzx/vtswebapi_configserver_repository
          default-label: main